server {
	listen 80;
	listen [::]:80;
	server_name blog.silentflare.com;
	access_log /var/log/nginx/silentflare-blog.access.log;
	error_log /var/log/nginx/silentflare-blog.error.log;
	include /etc/nginx/snippets/silentflare-shield-blog.conf;
}

server {
	listen 443 ssl;
	listen [::]:443 ssl;
	server_name blog.silentflare.com;
	ssl_certificate /etc/nginx/ssl/silentflare-selfsigned.crt;
	ssl_certificate_key /etc/nginx/ssl/silentflare-selfsigned.key;
	access_log /var/log/nginx/silentflare-blog.access.log;
	error_log /var/log/nginx/silentflare-blog.error.log;
	include /etc/nginx/snippets/silentflare-shield-blog.conf;
}
