server {
	listen 80;
	listen [::]:80;
	server_name shield.silentflare.com;
	access_log /var/log/nginx/silentflare-shield-portal.access.log;
	error_log /var/log/nginx/silentflare-shield-portal.error.log;
	include /etc/nginx/snippets/silentflare-shield-edge.conf;
}

server {
	listen 443 ssl;
	listen [::]:443 ssl;
	server_name shield.silentflare.com;
	ssl_certificate /etc/nginx/ssl/silentflare-selfsigned.crt;
	ssl_certificate_key /etc/nginx/ssl/silentflare-selfsigned.key;
	access_log /var/log/nginx/silentflare-shield-portal.access.log;
	error_log /var/log/nginx/silentflare-shield-portal.error.log;
	include /etc/nginx/snippets/silentflare-shield-edge.conf;
}
