server {
	listen 80;
	listen [::]:80;
	server_name cms.silentflare.com;
	client_max_body_size 50m;
	include /etc/nginx/snippets/silentflare-shield-cms.conf;
}

server {
	listen 443 ssl;
	listen [::]:443 ssl;
	server_name cms.silentflare.com;
	ssl_certificate /etc/nginx/ssl/silentflare-selfsigned.crt;
	ssl_certificate_key /etc/nginx/ssl/silentflare-selfsigned.key;
	access_log /var/log/nginx/silentflare-cms.access.log;
	error_log /var/log/nginx/silentflare-cms.error.log;
	client_max_body_size 50m;
	include /etc/nginx/snippets/silentflare-shield-cms.conf;
}
